version: '3.8'
services:
  api:
    image: localhost:5000/api:latest
    restart: always
    secrets:
    - source: api.env
    - target: /opt/app/.env
    ports:
    - 3002:3002
    networks:
      - myNetwork
    depends_on:
      - rmq
  rmq:
    image: rabbitmq:3-management
    restart: always
    profiles:
      - queue
    networks:
      - myNetwork
    environment:
      - USER=admin
      - PASSWORD=admin

networks:
  myNetwork:
    driver: overlay

secrets:
  api.env:
    external: true