galaxy_info:
  role_name: deploy
  description: Deploy microservices on Docker cluster
  author: Sharpovich
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: Ubuntu
      versions:
        - all