---
- name: Install Docker
  block:
    - name: Add universe
      apt_repository:
        repo: >
          deb http://us.archive.ubuntu.com/ubuntu/ 
          {{ ansible_distribution_release }} universe
        state: present
      tags: universe

    - name: Install packages
      apt: 
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update-cache: true
        cache_valid_time: 86400

    - name: Add docker key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Install stability repository
      apt_repository:
        repo: >
          deb [arch=amd64
          signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker

    - name: Install Docker-ce
      apt: 
        name: docker-ce
        update-cache: true
    - name: Check Docker installed
      service: 
        name: docker
        state: restated
        enabled: true
  become: true

- name: Install Docker-compose
  block:
    - name: Get last version docker-compose
      uri:
        url: http://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: page

    - name: Install docker-compose
      get_url:
        url: >
          https://github.com/docker/compose/releases/download/
          {{ page.json.tag_name }}/docker-compose-linux-x86_64
        dest: /use/local/bin/docker-compose
        mode: 0755
  become: true

- name: Setting extra packages python
  block:
    - name: Install pip packages
      pip:
        name: docker

- name: End install
  block:
    - name: Add user in group Docker
      user:
        name: "{{ ansible_user}}"
        groups: docker
        append: true
    - name: Reboot server
      reboot:
  become: true