apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp-deployment
  namespace: rolling
  labels:
    app: pyapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: sharpov210/lesson1
        ports:
        - containerPort: 8080
