---
- name: "[{{ name }}] configure config"
  include: "../config.yaml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: config_item
- name: "[{{ name }}] deploy service"
  block:
    - name: "[{{ name }}] deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "nginx:{{ version }}"
        state: present
        network:
          - name: "{{ network_name }}"
        publish: 
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
        configs:
          - config_name: nginx.conf
            filename: "etc/nginx/nginx.conf"
      tags: "{{ name }}"