galaxy_info:
  role_name: preconfig
  description: Prepared servers for work with Docker
  author: Sharpovich
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: Ubuntu
      versions:
        - all
dependencies:
  - role: deploy