apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lesson14
  labels:
    app: pyweb
spec:
  containers:
    - name: web
      image: sharpov210/lesson1:v0.1
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
